SET S(SSS)  'Seasons in the simulation'                                                        
/                                                                                              
*S01                                                                                           
S03,S07,S11,S15,S20,S24,S28,S33,S37,S42,S46,S50                                                                                 
*S02,S15,S25                                                                                   
/;                                                                                             
